name: Run SerenityBDD Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Chrome and ChromeDriver (matching versions)
        uses: browser-actions/setup-chrome@latest

      - name: Verify Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Set ChromeDriver Path
        run: echo "CHROMEDRIVER_PATH=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Verify current directory and permissions
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          chmod +x gradlew

      - name: Verify Java and Gradle versions
        run: |
          java -version
          ./gradlew --version

      - name: Run tests with Gradle
        env:
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
        run: ./gradlew clean test aggregate --stacktrace
        continue-on-error: true

      - name: Verify if Serenity reports exist
        run: |
          if [ -d "target/site/serenity" ]; then
            echo "Serenity reports found!"
          else
            echo "No Serenity reports found. Skipping upload step."
            exit 0
          fi

      - name: Upload Serenity Report
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
        continue-on-error: true